// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using edu_connect_service.Api.Data;

#nullable disable

namespace educonnectservice.Api.Data.Migrations
{
    [DbContext(typeof(edu_connect_serviceContext))]
    partial class edu_connect_serviceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("edu_connect_service.Api.Models.Administrador", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("usuario_id");

                    b.Property<string>("PasswordFase2Hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("password_fase2_hash");

                    b.HasKey("UsuarioId");

                    b.ToTable("administradores", (string)null);
                });

            modelBuilder.Entity("edu_connect_service.Api.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("edu_connect_service.Api.Models.EstadoSesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("estados_sesiones", (string)null);
                });

            modelBuilder.Entity("edu_connect_service.Api.Models.EstadoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("estados_usuarios", (string)null);
                });

            modelBuilder.Entity("edu_connect_service.Api.Models.Estudiante", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Carnet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("carnet");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("direccion");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("DATE")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("FotografiaUrl")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("fotografia_url");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("genero");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("telefono");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Carnet")
                        .IsUnique();

                    b.ToTable("estudiantes", (string)null);
                });

            modelBuilder.Entity("edu_connect_service.Api.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("edu_connect_service.Api.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("materias", (string)null);
                });

            modelBuilder.Entity("edu_connect_service.Api.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("edu_connect_service.Api.Models.Sesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("estado_id");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("estudiante_id");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaSesion")
                        .HasColumnType("DATE")
                        .HasColumnName("fecha_sesion");

                    b.Property<TimeSpan?>("HoraFin")
                        .HasColumnType("INTERVAL DAY(0) TO SECOND(0)")
                        .HasColumnName("hora_fin");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("INTERVAL DAY(0) TO SECOND(0)")
                        .HasColumnName("hora_inicio");

                    b.Property<int>("MateriaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("materia_id");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("motivo");

                    b.Property<string>("Resumen")
                        .HasColumnType("CLOB")
                        .HasColumnName("resumen");

                    b.Property<int>("TutorId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("tutor_id");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("MateriaId");

                    b.HasIndex("TutorId");

                    b.ToTable("sesiones", (string)null);
                });

            modelBuilder.Entity("edu_connect_service.Api.Models.Tutor", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("usuario_id");

                    b.Property<int>("AnioInicio")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("anio_inicio");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("CarnetId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("carnet_id");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("DireccionTutoria")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("direccion_tutoria");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("DATE")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("FotografiaUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("fotografia_url");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("genero");

                    b.Property<TimeSpan?>("HoraFin")
                        .HasColumnType("INTERVAL DAY(0) TO SECOND(0)")
                        .HasColumnName("hora_fin");

                    b.Property<TimeSpan?>("HoraInicio")
                        .HasColumnType("INTERVAL DAY(0) TO SECOND(0)")
                        .HasColumnName("hora_inicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("numero_identificacion");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("Universidad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("universidad");

                    b.HasKey("UsuarioId");

                    b.HasIndex("CarnetId")
                        .IsUnique();

                    b.HasIndex("NumeroIdentificacion")
                        .IsUnique();

                    b.ToTable("tutores", null, t =>
                        {
                            t.HasCheckConstraint("check_rango_horario", "\"hora_fin\" > \"hora_inicio\"");
                        });
                });

            modelBuilder.Entity("edu_connect_service.Api.Models.TutorDiaAtencion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiaSemana")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("dia_semana");

                    b.Property<int>("TutorId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("tutor_id");

                    b.HasKey("Id");

                    b.HasIndex("TutorId", "DiaSemana")
                        .IsUnique();

                    b.ToTable("tutores_dias_atencion", null, t =>
                        {
                            t.HasCheckConstraint("check_dia_semana", "\"dia_semana\" BETWEEN 1 AND 7");
                        });
                });

            modelBuilder.Entity("edu_connect_service.Api.Models.TutorMateria", b =>
                {
                    b.Property<int>("TutorId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("tutor_id");

                    b.Property<int>("MateriaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("materia_id");

                    b.HasKey("TutorId", "MateriaId");

                    b.HasIndex("MateriaId");

                    b.ToTable("tutores_materias", (string)null);
                });

            modelBuilder.Entity("edu_connect_service.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("correo");

                    b.Property<int>("EstadoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("estado_id");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("fecha_baja");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("MotivoBaja")
                        .HasColumnType("CLOB")
                        .HasColumnName("motivo_baja");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RolId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("rol_id");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("EstadoId");

                    b.HasIndex("RolId");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("edu_connect_service.Api.Models.Administrador", b =>
                {
                    b.HasOne("edu_connect_service.Api.Models.Usuario", "Usuario")
                        .WithOne("Administrador")
                        .HasForeignKey("edu_connect_service.Api.Models.Administrador", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("edu_connect_service.Api.Models.Estudiante", b =>
                {
                    b.HasOne("edu_connect_service.Api.Models.Usuario", "Usuario")
                        .WithOne("Estudiante")
                        .HasForeignKey("edu_connect_service.Api.Models.Estudiante", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("edu_connect_service.Api.Models.Item", b =>
                {
                    b.HasOne("edu_connect_service.Api.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("edu_connect_service.Api.Models.Sesion", b =>
                {
                    b.HasOne("edu_connect_service.Api.Models.EstadoSesion", "Estado")
                        .WithMany("Sesiones")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("edu_connect_service.Api.Models.Estudiante", "Estudiante")
                        .WithMany("Sesiones")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edu_connect_service.Api.Models.Materia", "Materia")
                        .WithMany("Sesiones")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edu_connect_service.Api.Models.Tutor", "Tutor")
                        .WithMany("Sesiones")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Estudiante");

                    b.Navigation("Materia");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("edu_connect_service.Api.Models.Tutor", b =>
                {
                    b.HasOne("edu_connect_service.Api.Models.Usuario", "Usuario")
                        .WithOne("Tutor")
                        .HasForeignKey("edu_connect_service.Api.Models.Tutor", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("edu_connect_service.Api.Models.TutorDiaAtencion", b =>
                {
                    b.HasOne("edu_connect_service.Api.Models.Tutor", "Tutor")
                        .WithMany("DiasAtencion")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("edu_connect_service.Api.Models.TutorMateria", b =>
                {
                    b.HasOne("edu_connect_service.Api.Models.Materia", "Materia")
                        .WithMany("TutorMaterias")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edu_connect_service.Api.Models.Tutor", "Tutor")
                        .WithMany("TutorMaterias")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("edu_connect_service.Api.Models.Usuario", b =>
                {
                    b.HasOne("edu_connect_service.Api.Models.EstadoUsuario", "Estado")
                        .WithMany("Usuarios")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("edu_connect_service.Api.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("edu_connect_service.Api.Models.EstadoSesion", b =>
                {
                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("edu_connect_service.Api.Models.EstadoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("edu_connect_service.Api.Models.Estudiante", b =>
                {
                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("edu_connect_service.Api.Models.Materia", b =>
                {
                    b.Navigation("Sesiones");

                    b.Navigation("TutorMaterias");
                });

            modelBuilder.Entity("edu_connect_service.Api.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("edu_connect_service.Api.Models.Tutor", b =>
                {
                    b.Navigation("DiasAtencion");

                    b.Navigation("Sesiones");

                    b.Navigation("TutorMaterias");
                });

            modelBuilder.Entity("edu_connect_service.Api.Models.Usuario", b =>
                {
                    b.Navigation("Administrador");

                    b.Navigation("Estudiante");

                    b.Navigation("Tutor");
                });
#pragma warning restore 612, 618
        }
    }
}
